version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: wordle-postgres
    environment:
      POSTGRES_DB: wordle
      POSTGRES_USER: wordle_user
      POSTGRES_PASSWORD: wordle_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wordle_user -d wordle"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Future: Add your Go application service here
  # wordle-app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgres://wordle_user:wordle_password@postgres:5432/wordle

volumes:
  postgres_data:
